In [1]:
import requests
import pandas as pd
from pandas import json_normalize


# === 1. MASUKKAN TOKEN DARI DASHBOARD CRM ===
# Masuk ke https://crm.qontak.com → Settings → API Token → Generate Token
# Token berlaku 6 jam
API_TOKEN = "62f2723b77ca522759653544007fedcf40e24a8f0f405aeaba9f65984dc6134e"

# === 2. ENDPOINT DAN PARAMETER ===
url = "https://app.qontak.com/api/v3.1/tasks?filter=alltask&page=1&per_page=100"

headers = {
    "Authorization": f"Bearer {API_TOKEN}",  # <-- Bearer token
    "Accept": "application/json"
}

# === 3. LAKUKAN REQUEST KE API ===
response = requests.get(url, headers=headers)

# === 4. CEK HASILNYA ===
content_type = response.headers.get("Content-Type", "")

if response.status_code == 200 and "application/json" in content_type:
    data = response.json()
    
    # Ubah ke DataFrame untuk tampilan tabel
    df = json_normalize(data["response"])

In [2]:
df

,id,name,created_at,updated_at,crm_person_id,crm_person_full_name,crm_deal_id,crm_deal_name,crm_company_id,crm_company_name,...,crm_team_ids,crm_team_name,due_date,reminder_date,detail,crm_checkin_attributes,next_step,attachment,unique_task_id,additional_fields
0,7781826,LE_Astra_Aurel,2025-10-24T11:12:27.595+07:00,2025-10-24T13:23:45.484+07:00,103466648,None,72548361,None,2647978,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,163ANTYPHT,"[{'id': 13616403, 'name': 'convert_to', 'value..."
1,7780295,Pres_PTBA_Hasan,2025-10-24T08:35:40.290+07:00,2025-10-24T12:58:33.365+07:00,51752069,None,71192168,None,2440568,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,2025-10-24T00:00:00.000+07:00,,None,,None,965DERSOTH,"[{'id': 13616403, 'name': 'convert_to', 'value..."
2,7781806,LE_Erajaya_Diky,2025-10-24T11:11:05.207+07:00,2025-10-24T12:55:27.519+07:00,50848644,None,72548617,None,2732520,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,728XEYMPTU,"[{'id': 13616403, 'name': 'convert_to', 'value..."
3,7782545,P_API_Delia,2025-10-24T12:47:04.256+07:00,2025-10-24T12:47:04.256+07:00,67221828,None,65319553,None,3088885,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,905HUPSYNN,"[{'id': 13616403, 'name': 'convert_to', 'value..."
4,7780100,LE_LPS_Heris,2025-10-24T07:59:58.586+07:00,2025-10-24T12:45:43.676+07:00,54906763,None,70999623,None,2780675,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,946LOTAVEN,"[{'id': 13616403, 'name': 'convert_to', 'value..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7769770,LE_Berdikari_Teddy,2025-10-22T08:11:35.655+07:00,2025-10-23T15:10:34.994+07:00,104470730,None,72609844,None,3179118,None,...,[9133],[Sales Team],2025-10-23T00:00:00.000+07:00,None,,None,,None,154PARDENE,"[{'id': 13616403, 'name': 'convert_to', 'value..."
96,7769772,P_Berdikari_Teddy,2025-10-22T08:12:26.530+07:00,2025-10-23T15:10:28.157+07:00,104470730,None,72609844,None,3179118,None,...,[9133],[Sales Team],2025-10-23T00:00:00.000+07:00,None,,None,,None,755NICKING,"[{'id': 13616403, 'name': 'convert_to', 'value..."
97,7773636,Pres_Dexa_Nelfina,2025-10-22T16:04:12.016+07:00,2025-10-23T14:50:31.192+07:00,55015414,None,70721264,None,2439309,None,...,[9133],[Sales Team],2025-10-23T00:00:00.000+07:00,None,,None,,None,322FRANDUN,"[{'id': 13616403, 'name': 'convert_to', 'value..."
98,7778089,Prop_PT Astemo Bekasi Mfg_Sugiarno Agung Wibowo,2025-10-23T14:36:58.513+07:00,2025-10-23T14:36:58.513+07:00,104526443,None,72619405,None,3232932,None,...,[9133],[Sales Team],2025-10-23T08:00:00.000+07:00,None,<p>a. Arrange SPH dan kirim via email bersama ...,None,,None,259URRESAL,"[{'id': 13616403, 'name': 'convert_to', 'value..."
99,7778073,M_PT Astemo Bekasi Mfg_Sugiarno Agung Wibowo,2025-10-23T14:35:16.121+07:00,2025-10-23T14:35:16.121+07:00,104526443,None,72619405,None,3232932,None,...,[9133],[Sales Team],2025-10-23T08:00:00.000+07:00,None,<p>Short call untuk sync informations.</p>,None,<p>a. Needs: seminar Pak In untuk bisa educati...,None,578DEARTHE,"[{'id': 13616403, 'name': 'convert_to', 'value..."

In [3]:
import requests
import pandas as pd

In [4]:
data

{'meta': {'status': 200,
  'type': 'OK',
  'error_code': None,
  'info': 'https://developers.qontak.com/docs/api/response-codes#200',
  'developer_message': 'Success',
  'message': 'Success',
  'timestamp': '2025-10-24T06:25:21.000+00:00',
  'log_id': 'd47ad1dc-c403-4d1c-b016-a681aaea981frails5'},
 'response': [{'id': '7781826',
   'name': 'LE_Astra_Aurel',
   'created_at': '2025-10-24T11:12:27.595+07:00',
   'updated_at': '2025-10-24T13:23:45.484+07:00',
   'crm_person_id': 103466648,
   'crm_person_full_name': None,
   'crm_deal_id': 72548361,
   'crm_deal_name': None,
   'crm_company_id': 2647978,
   'crm_company_name': None,
   'crm_task_status_id': 4,
   'user_id': 171113,
   'user_full_name': 'Yunita Ihtiarini',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '163ANTYPHT',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780295',
   'name': 'Pres_PTBA_Hasan',
   'created_at': '2025-10-24T08:35:40.290+07:00',
   'updated_at': '2025-10-24T12:58:33.365+07:00',
   'crm_person_id': 51752069,
   'crm_person_full_name': None,
   'crm_deal_id': 71192168,
   'crm_deal_name': None,
   'crm_company_id': 2440568,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 171363,
   'user_full_name': 'Reza Restuhadi',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': '2025-10-24T00:00:00.000+07:00',
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '965DERSOTH',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866818',
     'value_name': 'Presentation'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7781806',
   'name': 'LE_Erajaya_Diky',
   'created_at': '2025-10-24T11:11:05.207+07:00',
   'updated_at': '2025-10-24T12:55:27.519+07:00',
   'crm_person_id': 50848644,
   'crm_person_full_name': None,
   'crm_deal_id': 72548617,
   'crm_deal_name': None,
   'crm_company_id': 2732520,
   'crm_company_name': None,
   'crm_task_status_id': 4,
   'user_id': 171113,
   'user_full_name': 'Yunita Ihtiarini',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '728XEYMPTU',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7782545',
   'name': 'P_API_Delia',
   'created_at': '2025-10-24T12:47:04.256+07:00',
   'updated_at': '2025-10-24T12:47:04.256+07:00',
   'crm_person_id': 67221828,
   'crm_person_full_name': None,
   'crm_deal_id': 65319553,
   'crm_deal_name': None,
   'crm_company_id': 3088885,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 171113,
   'user_full_name': 'Yunita Ihtiarini',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '905HUPSYNN',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866815',
     'value_name': 'Prospect'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780100',
   'name': 'LE_LPS_Heris',
   'created_at': '2025-10-24T07:59:58.586+07:00',
   'updated_at': '2025-10-24T12:45:43.676+07:00',
   'crm_person_id': 54906763,
   'crm_person_full_name': None,
   'crm_deal_id': 70999623,
   'crm_deal_name': None,
   'crm_company_id': 2780675,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 222919,
   'user_full_name': 'Cantika Lila',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '946LOTAVEN',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780081',
   'name': 'D_PIS_wahyu tri wibowo',
   'created_at': '2025-10-24T07:52:40.128+07:00',
   'updated_at': '2025-10-24T12:45:15.030+07:00',
   'crm_person_id': 101649960,
   'crm_person_full_name': None,
   'crm_deal_id': 72002230,
   'crm_deal_name': None,
   'crm_company_id': 2647456,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 222919,
   'user_full_name': 'Cantika Lila',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '152GNALVEG',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866819',
     'value_name': 'Deal'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780084',
   'name': 'D_Pertamina Job Tomori_S_Anton Sugondo',
   'created_at': '2025-10-24T07:53:42.106+07:00',
   'updated_at': '2025-10-24T12:45:09.116+07:00',
   'crm_person_id': 103332350,
   'crm_person_full_name': None,
   'crm_deal_id': 72391848,
   'crm_deal_name': None,
   'crm_company_id': 2577429,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 222919,
   'user_full_name': 'Cantika Lila',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '597TTERARK',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866819',
     'value_name': 'Deal'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780348',
   'name': 'LE_Hasnur_Gusnevyanti',
   'created_at': '2025-10-24T08:42:37.798+07:00',
   'updated_at': '2025-10-24T12:45:03.571+07:00',
   'crm_person_id': 84017428,
   'crm_person_full_name': None,
   'crm_deal_id': 68653069,
   'crm_deal_name': None,
   'crm_company_id': 2706996,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 222919,
   'user_full_name': 'Cantika Lila',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '969OLARBON',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7781816',
   'name': 'LE_ITDC_Zahir',
   'created_at': '2025-10-24T11:11:47.054+07:00',
   'updated_at': '2025-10-24T12:43:57.619+07:00',
   'crm_person_id': 58105032,
   'crm_person_full_name': None,
   'crm_deal_id': 72548412,
   'crm_deal_name': None,
   'crm_company_id': 2828908,
   'crm_company_name': None,
   'crm_task_status_id': 4,
   'user_id': 171113,
   'user_full_name': 'Yunita Ihtiarini',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '779STUAMRO',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7782276',
   'name': 'LE_Pertamina_Jufe',
   'created_at': '2025-10-24T12:02:22.658+07:00',
   'updated_at': '2025-10-24T12:04:54.348+07:00',
   'crm_person_id': 47939779,
   'crm_person_full_name': None,
   'crm_deal_id': 72718511,
   'crm_deal_name': None,
   'crm_company_id': 2439247,
   'crm_company_name': None,
   'crm_task_status_id': 4,
   'user_id': 171110,
   'user_full_name': 'Anindya Kirana',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '521EXPOSTI',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7782281',
   'name': 'P_Pertamina_jufe',
   'created_at': '2025-10-24T12:03:12.128+07:00',
   'updated_at': '2025-10-24T12:04:04.771+07:00',
   'crm_person_id': 47939779,
   'crm_person_full_name': None,
   'crm_deal_id': 72718511,
   'crm_deal_name': None,
   'crm_company_id': 2439247,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 171110,
   'user_full_name': 'Anindya Kirana',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '969NAMEWSM',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866815',
     'value_name': 'Prospect'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866825',
     'value_name': 'Invite to Event'}]},
  {'id': '7780133',
   'name': 'IV_BSI_Indra',
   'created_at': '2025-10-24T08:07:44.598+07:00',
   'updated_at': '2025-10-24T11:58:06.291+07:00',
   'crm_person_id': 50803181,
   'crm_person_full_name': None,
   'crm_deal_id': 70810574,
   'crm_deal_name': None,
   'crm_company_id': 2534554,
   'crm_company_name': None,
   'crm_task_status_id': 4,
   'user_id': 171110,
   'user_full_name': 'Anindya Kirana',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '138RRYMENB',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866820',
     'value_name': 'Invoice'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866822',
     'value_name': 'Visit'}]},
  {'id': '7780088',
   'name': 'I_PAM Jaya_C_Ahmad Naufal',
   'created_at': '2025-10-24T07:55:06.009+07:00',
   'updated_at': '2025-10-24T11:45:15.081+07:00',
   'crm_person_id': 89998367,
   'crm_person_full_name': None,
   'crm_deal_id': 70063929,
   'crm_deal_name': None,
   'crm_company_id': 3195772,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 222919,
   'user_full_name': 'Cantika Lila',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T00:00:00.000+07:00',
   'reminder_date': None,
   'detail': '',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '344SCIETYI',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866820',
     'value_name': 'Invoice'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780066',
   'name': 'P_Astra Daihatsu Motor_Isa Nova',
   'created_at': '2025-10-24T07:48:30.222+07:00',
   'updated_at': '2025-10-24T11:28:48.803+07:00',
   'crm_person_id': 79327239,
   'crm_person_full_name': None,
   'crm_deal_id': 67736238,
   'crm_deal_name': None,
   'crm_company_id': 2756484,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 233929,
   'user_full_name': 'Mawaddah Dhuha Rahmarilla',
   'crm_task_priority_id': 3,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T08:00:00.000+07:00',
   'reminder_date': None,
   'detail': '<p>Engagement by inviting ke Masterclass IC\xa0</p>',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '794DIBETON',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866815',
     'value_name': 'Prospect'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866825',
     'value_name': 'Invite to Event'}]},
  {'id': '7780085',
   'name': 'P_Kawasan Berikat Nusantara_Andi Rifa',
   'created_at': '2025-10-24T07:53:59.987+07:00',
   'updated_at': '2025-10-24T11:28:40.235+07:00',
   'crm_person_id': 61327404,
   'crm_person_full_name': None,
   'crm_deal_id': 72526411,
   'crm_deal_name': None,
   'crm_company_id': 2865105,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 233929,
   'user_full_name': 'Mawaddah Dhuha Rahmarilla',
   'crm_task_priority_id': 3,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T08:00:00.000+07:00',
   'reminder_date': None,
   'detail': '<p>Engagement by inviting ke Masterclass IC\xa0</p>',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '419CANDYST',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866815',
     'value_name': 'Prospect'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7780036',
   'name': 'P_Wahana Artha Group_Selvy Wahjuni',
   'created_at': '2025-10-24T07:44:46.871+07:00',
   'updated_at': '2025-10-24T11:28:33.003+07:00',
   'crm_person_id': 99934328,
   'crm_person_full_name': None,
   'crm_deal_id': 71581956,
   'crm_deal_name': None,
   'crm_company_id': 3197467,
   'crm_company_name': None,
   'crm_task_status_id': 2,
   'user_id': 233929,
   'user_full_name': 'Mawaddah Dhuha Rahmarilla',
   'crm_task_priority_id': 3,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T08:00:00.000+07:00',
   'reminder_date': None,
   'detail': '<p>Engagement by inviting ke Masterclass IC\xa0</p>',
   'crm_checkin_attributes': None,
   'next_step': '',
   'attachment': None,
   'unique_task_id': '541VENSIOU',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866815',
     'value_name': 'Prospect'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866825',
     'value_name': 'Invite to Event'}]},
  {'id': '7781962',
   'name': 'Press_TelkomInfra_Wahyu',
   'created_at': '2025-10-24T11:25:35.258+07:00',
   'updated_at': '2025-10-24T11:25:35.258+07:00',
   'crm_person_id': 77300304,
   'crm_person_full_name': None,
   'crm_deal_id': 67323405,
   'crm_deal_name': None,
   'crm_company_id': 3142104,
   'crm_company_name': None,
   'crm_task_status_id': 1,
   'user_id': 251373,
   'user_full_name': 'Muhammad\xa0 Naim',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T08:00:00.000+07:00',
   'reminder_date': '2025-10-24T07:30:00.000+07:00',
   'detail': '<p>Fu utnuk presentasi</p>',
   'crm_checkin_attributes': None,
   'next_step': '<p>R, respon</p>\r\n<p>N, presentasi dan deal</p>',
   'attachment': None,
   'unique_task_id': '296IFIEMIL',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866818',
     'value_name': 'Presentation'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7781949',
   'name': 'LE_Ekacitta_Pungkas',
   'created_at': '2025-10-24T11:24:22.786+07:00',
   'updated_at': '2025-10-24T11:24:42.632+07:00',
   'crm_person_id': 102715759,
   'crm_person_full_name': None,
   'crm_deal_id': 49373312,
   'crm_deal_name': None,
   'crm_company_id': 2573369,
   'crm_company_name': None,
   'crm_task_status_id': 1,
   'user_id': 251373,
   'user_full_name': 'Muhammad\xa0 Naim',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T08:00:00.000+07:00',
   'reminder_date': '2025-10-24T07:30:00.000+07:00',
   'detail': '<p>Whatsapp dan kenalana lagi</p>',
   'crm_checkin_attributes': None,
   'next_step': '<p>R, respon</p>\r\n<p>N, prospek</p>',
   'attachment': None,
   'unique_task_id': '992ENBERAL',
   'additional_fields': [{'id': 13616403,
     'name': 'convert_to',
     'value': '3866814',
     'value_name': 'Lead Engaged'},
    {'id': 13616418,
     'name': 'engagement_type',
     'value': '3866823',
     'value_name': 'Personal Engagement'}]},
  {'id': '7781934',
   'name': 'P_Arutmin Indonesia_Sukri',
   'created_at': '2025-10-24T11:22:57.158+07:00',
   'updated_at': '2025-10-24T11:22:57.158+07:00',
   'crm_person_id': 98024372,
   'crm_person_full_name': None,
   'crm_deal_id': 71189624,
   'crm_deal_name': None,
   'crm_company_id': 3212610,
   'crm_company_name': None,
   'crm_task_status_id': 1,
   'user_id': 251373,
   'user_full_name': 'Muhammad\xa0 Naim',
   'crm_task_priority_id': 1,
   'crm_task_category_id': None,
   'crm_task_category_name': None,
   'crm_team_ids': [9133],
   'crm_team_name': ['Sales Team'],
   'due_date': '2025-10-24T08:00:00.000+07:00',

In [5]:
df = json_normalize(data["response"])

print("Jumlah baris:", len(df))
display(df.head())

Jumlah baris: 100

,id,name,created_at,updated_at,crm_person_id,crm_person_full_name,crm_deal_id,crm_deal_name,crm_company_id,crm_company_name,...,crm_team_ids,crm_team_name,due_date,reminder_date,detail,crm_checkin_attributes,next_step,attachment,unique_task_id,additional_fields
0,7781826,LE_Astra_Aurel,2025-10-24T11:12:27.595+07:00,2025-10-24T13:23:45.484+07:00,103466648,None,72548361,None,2647978,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,163ANTYPHT,"[{'id': 13616403, 'name': 'convert_to', 'value..."
1,7780295,Pres_PTBA_Hasan,2025-10-24T08:35:40.290+07:00,2025-10-24T12:58:33.365+07:00,51752069,None,71192168,None,2440568,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,2025-10-24T00:00:00.000+07:00,,None,,None,965DERSOTH,"[{'id': 13616403, 'name': 'convert_to', 'value..."
2,7781806,LE_Erajaya_Diky,2025-10-24T11:11:05.207+07:00,2025-10-24T12:55:27.519+07:00,50848644,None,72548617,None,2732520,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,728XEYMPTU,"[{'id': 13616403, 'name': 'convert_to', 'value..."
3,7782545,P_API_Delia,2025-10-24T12:47:04.256+07:00,2025-10-24T12:47:04.256+07:00,67221828,None,65319553,None,3088885,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,905HUPSYNN,"[{'id': 13616403, 'name': 'convert_to', 'value..."
4,7780100,LE_LPS_Heris,2025-10-24T07:59:58.586+07:00,2025-10-24T12:45:43.676+07:00,54906763,None,70999623,None,2780675,None,...,[9133],[Sales Team],2025-10-24T00:00:00.000+07:00,None,,None,,None,946LOTAVEN,"[{'id': 13616403, 'name': 'convert_to', 'value..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      100 non-null    object
 1   name                    100 non-null    object
 2   created_at              100 non-null    object
 3   updated_at              100 non-null    object
 4   crm_person_id           100 non-null    int64
 5   crm_person_full_name    0 non-null      object
 6   crm_deal_id             100 non-null    int64
 7   crm_deal_name           0 non-null      object
 8   crm_company_id          100 non-null    int64
 9   crm_company_name        0 non-null      object
 10  crm_task_status_id      100 non-null    int64
 11  user_id                 100 non-null    int64
 12  user_full_name          100 non-null    object
 13  crm_task_priority_id    100 non-null    int64
 14  crm_task_category_id    0 non-null      object
 15  crm_task_category_name  0 non-null      object
 16  crm_team_ids            100 non-null    object
 17  crm_team_name           100 non-null    object
 18  due_date                100 non-null    object
 19  reminder_date           30 non-null     object
 20  detail                  100 non-null    object
 21  crm_checkin_attributes  0 non-null      object
 22  next_step               100 non-null    object
 23  attachment              0 non-null      object
 24  unique_task_id          100 non-null    object
 25  additional_fields       100 non-null    object
dtypes: int64(6), object(20)
memory usage: 20.4+ KB

In [7]:
df.columns.to_list()

['id',
 'name',
 'created_at',
 'updated_at',
 'crm_person_id',
 'crm_person_full_name',
 'crm_deal_id',
 'crm_deal_name',
 'crm_company_id',
 'crm_company_name',
 'crm_task_status_id',
 'user_id',
 'user_full_name',
 'crm_task_priority_id',
 'crm_task_category_id',
 'crm_task_category_name',
 'crm_team_ids',
 'crm_team_name',
 'due_date',
 'reminder_date',
 'detail',
 'crm_checkin_attributes',
 'next_step',
 'attachment',
 'unique_task_id',
 'additional_fields']

In [8]:
add_field= df['additional_fields']

In [9]:
add_field

0     [{'id': 13616403, 'name': 'convert_to', 'value...
1     [{'id': 13616403, 'name': 'convert_to', 'value...
2     [{'id': 13616403, 'name': 'convert_to', 'value...
3     [{'id': 13616403, 'name': 'convert_to', 'value...
4     [{'id': 13616403, 'name': 'convert_to', 'value...
                            ...
95    [{'id': 13616403, 'name': 'convert_to', 'value...
96    [{'id': 13616403, 'name': 'convert_to', 'value...
97    [{'id': 13616403, 'name': 'convert_to', 'value...
98    [{'id': 13616403, 'name': 'convert_to', 'value...
99    [{'id': 13616403, 'name': 'convert_to', 'value...
Name: additional_fields, Length: 100, dtype: object

In [10]:
import pandas as pd

# Misal df adalah DataFrame kamu
# Contoh struktur kolom:
# df['additional_fields'] = [
#     [{'name': 'convert_to', 'value': 'USD'}, {'name': 'amount', 'value': 100}],
#     [{'name': 'convert_to', 'value': 'EUR'}, {'name': 'amount', 'value': 200}],
# ]

# Ubah list of dict di kolom 'additional_fields' menjadi dict tunggal
df_expanded = (
    df['additional_fields']
    .apply(lambda x: {d['name']: d.get('value', None) for d in x})
    .apply(pd.Series)
)

# Gabungkan kembali dengan DataFrame asli
df_final = pd.concat([df.drop(columns=['additional_fields']), df_expanded], axis=1)

# Jika ingin menyatukan kolom hasil menjadi satu string dengan koma
df_final['merged'] = df_expanded.apply(lambda row: ', '.join([f"{k}: {v}" for k, v in row.items() if pd.notnull(v)]), axis=1)

print(df_final.head())

        id             name                     created_at  \
0  7781826   LE_Astra_Aurel  2025-10-24T11:12:27.595+07:00
1  7780295  Pres_PTBA_Hasan  2025-10-24T08:35:40.290+07:00
2  7781806  LE_Erajaya_Diky  2025-10-24T11:11:05.207+07:00
3  7782545      P_API_Delia  2025-10-24T12:47:04.256+07:00
4  7780100     LE_LPS_Heris  2025-10-24T07:59:58.586+07:00

                      updated_at  crm_person_id crm_person_full_name  \
0  2025-10-24T13:23:45.484+07:00      103466648                 None
1  2025-10-24T12:58:33.365+07:00       51752069                 None
2  2025-10-24T12:55:27.519+07:00       50848644                 None
3  2025-10-24T12:47:04.256+07:00       67221828                 None
4  2025-10-24T12:45:43.676+07:00       54906763                 None

   crm_deal_id crm_deal_name  crm_company_id crm_company_name  ...  \
0     72548361          None         2647978             None  ...
1     71192168          None         2440568             None  ...
2     72548617          None         2732520             None  ...
3     65319553          None         3088885             None  ...
4     70999623          None         2780675             None  ...

                        due_date                  reminder_date detail  \
0  2025-10-24T00:00:00.000+07:00                           None
1  2025-10-24T00:00:00.000+07:00  2025-10-24T00:00:00.000+07:00
2  2025-10-24T00:00:00.000+07:00                           None
3  2025-10-24T00:00:00.000+07:00                           None
4  2025-10-24T00:00:00.000+07:00                           None

   crm_checkin_attributes next_step attachment unique_task_id convert_to  \
0                    None                 None     163ANTYPHT    3866814
1                    None                 None     965DERSOTH    3866818
2                    None                 None     728XEYMPTU    3866814
3                    None                 None     905HUPSYNN    3866815
4                    None                 None     946LOTAVEN    3866814

  engagement_type                                         merged
0         3866823  convert_to: 3866814, engagement_type: 3866823
1         3866823  convert_to: 3866818, engagement_type: 3866823
2         3866823  convert_to: 3866814, engagement_type: 3866823
3         3866823  convert_to: 3866815, engagement_type: 3866823
4         3866823  convert_to: 3866814, engagement_type: 3866823

[5 rows x 28 columns]

In [11]:
df_final

,id,name,created_at,updated_at,crm_person_id,crm_person_full_name,crm_deal_id,crm_deal_name,crm_company_id,crm_company_name,...,due_date,reminder_date,detail,crm_checkin_attributes,next_step,attachment,unique_task_id,convert_to,engagement_type,merged
0,7781826,LE_Astra_Aurel,2025-10-24T11:12:27.595+07:00,2025-10-24T13:23:45.484+07:00,103466648,None,72548361,None,2647978,None,...,2025-10-24T00:00:00.000+07:00,None,,None,,None,163ANTYPHT,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823"
1,7780295,Pres_PTBA_Hasan,2025-10-24T08:35:40.290+07:00,2025-10-24T12:58:33.365+07:00,51752069,None,71192168,None,2440568,None,...,2025-10-24T00:00:00.000+07:00,2025-10-24T00:00:00.000+07:00,,None,,None,965DERSOTH,3866818,3866823,"convert_to: 3866818, engagement_type: 3866823"
2,7781806,LE_Erajaya_Diky,2025-10-24T11:11:05.207+07:00,2025-10-24T12:55:27.519+07:00,50848644,None,72548617,None,2732520,None,...,2025-10-24T00:00:00.000+07:00,None,,None,,None,728XEYMPTU,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823"
3,7782545,P_API_Delia,2025-10-24T12:47:04.256+07:00,2025-10-24T12:47:04.256+07:00,67221828,None,65319553,None,3088885,None,...,2025-10-24T00:00:00.000+07:00,None,,None,,None,905HUPSYNN,3866815,3866823,"convert_to: 3866815, engagement_type: 3866823"
4,7780100,LE_LPS_Heris,2025-10-24T07:59:58.586+07:00,2025-10-24T12:45:43.676+07:00,54906763,None,70999623,None,2780675,None,...,2025-10-24T00:00:00.000+07:00,None,,None,,None,946LOTAVEN,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7769770,LE_Berdikari_Teddy,2025-10-22T08:11:35.655+07:00,2025-10-23T15:10:34.994+07:00,104470730,None,72609844,None,3179118,None,...,2025-10-23T00:00:00.000+07:00,None,,None,,None,154PARDENE,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823"
96,7769772,P_Berdikari_Teddy,2025-10-22T08:12:26.530+07:00,2025-10-23T15:10:28.157+07:00,104470730,None,72609844,None,3179118,None,...,2025-10-23T00:00:00.000+07:00,None,,None,,None,755NICKING,3866815,3866823,"convert_to: 3866815, engagement_type: 3866823"
97,7773636,Pres_Dexa_Nelfina,2025-10-22T16:04:12.016+07:00,2025-10-23T14:50:31.192+07:00,55015414,None,70721264,None,2439309,None,...,2025-10-23T00:00:00.000+07:00,None,,None,,None,322FRANDUN,3866818,3866823,"convert_to: 3866818, engagement_type: 3866823"
98,7778089,Prop_PT Astemo Bekasi Mfg_Sugiarno Agung Wibowo,2025-10-23T14:36:58.513+07:00,2025-10-23T14:36:58.513+07:00,104526443,None,72619405,None,3232932,None,...,2025-10-23T08:00:00.000+07:00,None,<p>a. Arrange SPH dan kirim via email bersama ...,None,,None,259URRESAL,3866817,3866823,"convert_to: 3866817, engagement_type: 3866823"
99,7778073,M_PT Astemo Bekasi Mfg_Sugiarno Agung Wibowo,2025-10-23T14:35:16.121+07:00,2025-10-23T14:35:16.121+07:00,104526443,None,72619405,None,3232932,None,...,2025-10-23T08:00:00.000+07:00,None,<p>Short call untuk sync informations.</p>,None,<p>a. Needs: seminar Pak In untuk bisa educati...,None,578DEARTHE,3866816,3866823,"convert_to: 3866816, engagement_type: 3866823"

3866820	 = Invoice
3866816	= Meeting Need
3866817	 Proposal Submitted
3866819 = Deal
3866818	= Presentation
3866814	= Lead Engaged
3866815 = Prospect

In [12]:
df_final.dtypes

id                        object
name                      object
created_at                object
updated_at                object
crm_person_id              int64
crm_person_full_name      object
crm_deal_id                int64
crm_deal_name             object
crm_company_id             int64
crm_company_name          object
crm_task_status_id         int64
user_id                    int64
user_full_name            object
crm_task_priority_id       int64
crm_task_category_id      object
crm_task_category_name    object
crm_team_ids              object
crm_team_name             object
due_date                  object
reminder_date             object
detail                    object
crm_checkin_attributes    object
next_step                 object
attachment                object
unique_task_id            object
convert_to                object
engagement_type           object
merged                    object
dtype: object

In [13]:
df_final["convert_to"] = pd.to_numeric(df_final["convert_to"], errors="coerce").astype("Int64")
df_final["engagement_type"] = pd.to_numeric(df_final["engagement_type"], errors="coerce").astype("Int64")

In [14]:
status_mapping = {
    1: "Belum Dimulai",
    2: "Dalam Proses",
    3: "Menunggu",
    4: "Selesai",
    5: "Ditunda"
}
df_final["crm_task_status"] = df_final["crm_task_status_id"].map(status_mapping)

In [15]:
mapping_convert = {
    3866814: "Lead Engaged",
    3866815: "Prospect",
    3866816: "Meeting Need",
    3866817: "Proposal Submitted",
    3866818: "Presentation",
    3866819: "Deal",
    3866820: "Invoice"}

df_final["convert_to_label"] = df_final["convert_to"].map(mapping_convert)

In [16]:
df_final

,id,name,created_at,updated_at,crm_person_id,crm_person_full_name,crm_deal_id,crm_deal_name,crm_company_id,crm_company_name,...,detail,crm_checkin_attributes,next_step,attachment,unique_task_id,convert_to,engagement_type,merged,crm_task_status,convert_to_label
0,7781826,LE_Astra_Aurel,2025-10-24T11:12:27.595+07:00,2025-10-24T13:23:45.484+07:00,103466648,None,72548361,None,2647978,None,...,,None,,None,163ANTYPHT,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823",Selesai,Lead Engaged
1,7780295,Pres_PTBA_Hasan,2025-10-24T08:35:40.290+07:00,2025-10-24T12:58:33.365+07:00,51752069,None,71192168,None,2440568,None,...,,None,,None,965DERSOTH,3866818,3866823,"convert_to: 3866818, engagement_type: 3866823",Dalam Proses,Presentation
2,7781806,LE_Erajaya_Diky,2025-10-24T11:11:05.207+07:00,2025-10-24T12:55:27.519+07:00,50848644,None,72548617,None,2732520,None,...,,None,,None,728XEYMPTU,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823",Selesai,Lead Engaged
3,7782545,P_API_Delia,2025-10-24T12:47:04.256+07:00,2025-10-24T12:47:04.256+07:00,67221828,None,65319553,None,3088885,None,...,,None,,None,905HUPSYNN,3866815,3866823,"convert_to: 3866815, engagement_type: 3866823",Dalam Proses,Prospect
4,7780100,LE_LPS_Heris,2025-10-24T07:59:58.586+07:00,2025-10-24T12:45:43.676+07:00,54906763,None,70999623,None,2780675,None,...,,None,,None,946LOTAVEN,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823",Dalam Proses,Lead Engaged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7769770,LE_Berdikari_Teddy,2025-10-22T08:11:35.655+07:00,2025-10-23T15:10:34.994+07:00,104470730,None,72609844,None,3179118,None,...,,None,,None,154PARDENE,3866814,3866823,"convert_to: 3866814, engagement_type: 3866823",Selesai,Lead Engaged
96,7769772,P_Berdikari_Teddy,2025-10-22T08:12:26.530+07:00,2025-10-23T15:10:28.157+07:00,104470730,None,72609844,None,3179118,None,...,,None,,None,755NICKING,3866815,3866823,"convert_to: 3866815, engagement_type: 3866823",Dalam Proses,Prospect
97,7773636,Pres_Dexa_Nelfina,2025-10-22T16:04:12.016+07:00,2025-10-23T14:50:31.192+07:00,55015414,None,70721264,None,2439309,None,...,,None,,None,322FRANDUN,3866818,3866823,"convert_to: 3866818, engagement_type: 3866823",Dalam Proses,Presentation
98,7778089,Prop_PT Astemo Bekasi Mfg_Sugiarno Agung Wibowo,2025-10-23T14:36:58.513+07:00,2025-10-23T14:36:58.513+07:00,104526443,None,72619405,None,3232932,None,...,<p>a. Arrange SPH dan kirim via email bersama ...,None,,None,259URRESAL,3866817,3866823,"convert_to: 3866817, engagement_type: 3866823",Dalam Proses,Proposal Submitted
99,7778073,M_PT Astemo Bekasi Mfg_Sugiarno Agung Wibowo,2025-10-23T14:35:16.121+07:00,2025-10-23T14:35:16.121+07:00,104526443,None,72619405,None,3232932,None,...,<p>Short call untuk sync informations.</p>,None,<p>a. Needs: seminar Pak In untuk bisa educati...,None,578DEARTHE,3866816,3866823,"convert_to: 3866816, engagement_type: 3866823",Selesai,Meeting Need

In [17]:
df_final['convert_to_label'].value_counts()

convert_to_label
Prospect              45
Lead Engaged          16
Deal                  12
Presentation          11
Meeting Need           6
Invoice                5
Proposal Submitted     5
Name: count, dtype: int64

In [18]:
pivot_table = pd.pivot_table(
        df_final,
        index="user_full_name",
        columns="crm_task_status",
        values="id",
        aggfunc="count",
        fill_value=0
    ).reset_index()

In [19]:
pivot_table

crm_task_status,user_full_name,Belum Dimulai,Dalam Proses,Selesai
0,Anindya Kirana,2,9,5
1,Cantika Lila,3,5,1
2,Mawaddah Dhuha Rahmarilla,10,9,1
3,Muhammad Naim,12,3,1
4,Reza Restuhadi,9,1,4
5,Wime Ega,2,0,6
6,Yunita Ihtiarini,4,7,6